package uz.zero.auth.enums


enum class ErrorCode(val code: Int, val message: String) {
    VALIDATION_ERROR(40, "VALIDATION_ERROR"),
    ROLE_KEY_ALREADY_EXISTS(100, "ROLE_KEY_ALREADY_EXISTS"),
    PERMISSION_GROUP_NOT_FOUND(101, "PERMISSION_GROUP_NOT_FOUND"),
    ROLE_NOT_FOUND(102, "ROLE_NOT_FOUND"),
    ROLE_HAS_RELATION_WITH_USER(103, "ROLE_HAS_RELATION_WITH_USER"),
    PERMISSION_GROUP_KEY_ALREADY_EXISTS(104, "PERMISSION_GROUP_KEY_ALREADY_EXISTS"),
    PERMISSION_KEY_ALREADY_EXIST(105, "PERMISSION_KEY_ALREADY_EXISTS"),
    PERMISSION_NOT_FOUND(106, "PERMISSION_NOT_FOUND"),
    ROLE_LEVEL_BIGGER_THAN_YOURS(107, "ROLE_LEVEL_BIGGER_THAN_YOURS"),
    USERNAME_ALREADY_TAKEN(108, "USERNAME_ALREADY_TAKEN"),
    USER_NOT_FOUND(109, "USER_NOT_FOUND"),
    USER_UPDATE_NOT_ALLOWED(110, "USER_UPDATE_NOT_ALLOWED"),
    CLIENT_ALREADY_EXISTS(111, "CLIENT_ALREADY_EXISTS"),
    CLIENT_NOT_FOUND(112, "CLIENT_NOT_FOUND"),
    PARTNER_NOT_FOUND(113, "PARTNER_NOT_FOUND"),
}