package org.example.organization

enum class EmployeeRole {
    CEO,
    EMPLOYEE
}
enum class ErrorCode(val code: Int, val message: String) {
    ORGANIZATION_ALREADY_EXISTS(100, "ORGANIZATION_ALREADY_EXISTS"),
    ORGANIZATION_NOT_FOUND(101, "ORGANIZATION_NOT_FOUND"),
    ORGANIZATION_NOT_ACTIVE(103, "ORGANIZATION_NOT_ACTIVE"),

    ////////

    EMPLOYEE_ALREADY_EXISTS(200, "EMPLOYEE_ALREADY_EXISTS"),
    EMPLOYEE_NOT_FOUND(201, "EMPLOYEE_NOT_FOUND"),
    EMPLOYEE_CONTEX_NOT_FOUND(202, "EMPLOYEE_CONTEX_NOT_FOUND"),
    EMPLOYEE_NOT_IN_ORGANIZATION(203, "EMPLOYEE_NOT_IN_ORGANIZATION"),
    USER_NOT_FOUND(204, "USER_NOT_FOUND"),
    ADMIN_CAN_NOT_BE_EMPLOYEE(205, "ADMIN_CAN_NOT_BE_EMPLOYEE"),

}

enum class Role {
    USER,
    ADMIN,
    DEVELOPER,
}