package org.example.project

enum class Permission{
    OWNER, ASSIGNED
}

enum class EmployeeRole {
    CEO,
    EMPLOYEE
}


enum class ErrorCode(val code: Int) {
    PROJECT_NOT_FOUND(400),
    BOARD_NOT_FOUND(401),
    TASK_STATE_NOT_FOUND(402),
    BOARD_TASK_STATE_NOT_FOUND(403),
    PROJECT_IS_NOT_ACTIVE(404),
    PROJECT_ENDED(405),
    STATE_IS_NOT_FIRST(406),
    STATE_NOT_CONNNECTED_TO_BOARD(407),
    NOT_PERMITED_TO_TRANSFER_TASK(408),
    ORDERS_OF_STATES_IS_INCORRECT(409),
    INVALID_STATE_POSITION(410),
    TEMPLATE_NAME_EXITS_EXEPTION(411),
    TEMPLATE_NOT_FOUND(412),
    USER_NOT_ALLOWED_TO_CREATE_PROJECT(413),
    EMPLOYEE_CANNOT_CREATE_BOARD(414),
    BOARD_NAME_ALREADY_EXISTS_IN_PROJECT(415),
    USER_ALREADY_ASSIGNED_TO_BOARD(416),
    USER_NOT_ASSIGNED_TO_BOARD(417),
    STATE_ALREADY_CONNECTED_TO_BOARD(418),
    USER_NOT_CEO_EXCEPTION(419),
    STATE_NAME_EXISTS_EXCEPTION(420)

}

enum class Role {
    USER,
    ADMIN,
    DEVELOPER,
}
